server:
  port: 9601
restConnectTime: 3000
serviceAddressBaseUri: "http://${serviceNode}-internal.vroozi.com"
webAddressBaseUri: "http://${webNode}-internal.vroozi.com"
erpAddressBaseUri: "http://${erpNode}-internal.vroozi.com"
catalogAddressBaseUri: "http://${catalogNode}-internal.vroozi.com"
storageBaseUri: "https://storage-stage.vroozi.com"
batchBaseUri: "http://${batchNode}-internal.vroozi.com"